project:
  type: website
  output-dir: docs

website:
  title: "IGNITE Symposium Vol. 2"
  navbar:
    left:
      - href: index.qmd
        text: Morbid Curioisty
      - href: about.qmd
        text: About      
      - creepy.qmd

format:
  html:
    theme: 
        light: flatly
        dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: true
    code-link: true
    code-tools: true


editor: visual

